### ISSUE TITLE
Configurable rules

### ISSUE THREAD

**Issue by johngluckmdsol** [funkwerk/gherkin_lint#7]
We'd like to submit a PR for your gem that will allow us to configure your gem with custom rules.  We'd do something like the following

1. Create a configuration file (.gherkin_lint) to set the name of additional directories to read rules from (this would be `lib/gherkin_lint/linter`).  
2. Make GherkinLint.LINTER dynamic (no longer a constant) and read a glob based on the directories in the configuration
3. Remove the --enable option.  All directories would be included and then --disable would be processed.  I'm not clear why the --enable option is necessary.

What do you think?

**Comment by lindt** [comment]
great ideas
1. what specific linters are needed? could these be made generic?
3. `--enable` is basically there for tests

**Comment by johngluckmdsol** [comment]
We want tests that make certain tags required and are looking towards a few more that are specific to our rules that wouldn't be applicable to the general population.  When I implement them, I'll see if there's a way to make them more generic, but I can't see a way to do this currently

**Comment by johngluckmdsol** [comment]
Okay, well we will try to keep --enable.

**Comment by johngluckmdsol** [comment]
@lindt Will you please take a look at our fork and let us know if you want this linter in your code base or whether you want us to load it in ourselves?

It's easier to put it in your code if you think other people might want it

**Comment by johngluckmdsol** [comment]
I think this can be closed no
