### ISSUE TITLE
Verbose success

### ISSUE THREAD

**Issue by johngluckmdsol** [funkwerk/gherkin_lint#9]
If there are no linters enabled or if the linters run and find nothing, gherkin_lint currently does nothing but it should say something like "No Linters were enabled" or "gherkin lint found no errors"

**Comment by johngluckmdsol** [comment]
This is fixed in my PR

**Comment by LukasRypl** [comment]
It seems to me that the GherkinLint@verbose is never set from the command line options.

I would love to create a PR but I am unable to run my local version.  It complains about problems with require statements after running `bin/gherkin_lint -v `:
```                                                                                                                                   
bin/gherkin_lint:2:in `require': cannot load such file -- gherkin_lint (LoadError)
	from bin/gherkin_lint:2:in `<main>'). 
```
How can I verify my local changes before I create PR? (yes, I have quite limited experience with gems, rake and alike - should I run `gem build gherkin_lint.gemspec` or `rake`?)

**Comment by johngluckmdsol** [comment]
You can run the features and specs before submitting your PR
`bundle exec cucumber`
`bundle exec rspec`
I just ran these on develop and they are passing

I am not sure why you are having trouble with running the executable.  I just tried it and had no such problem.  Did you run `bundle install`?

Also, I just ran with the -v setting and it's working fine for me.  But you need to understand that the verbose setting is not the tradition verbose setting and it actually a verbose success, meaning that it ran even when no linters are enabled or when it didn't find errors.  Before this feature, it was succeeding silently
